version: "3.7"

x-arguments: &arguments
  args:
    GID: ${GID}
    UID: ${UID}
    GIT_EMAIL: ${GIT_EMAIL}
    GIT_NAME: ${GIT_NAME}
    XDEBUG_HOST: ${XDEBUG_HOST}
    XDEBUG_PORT: ${XDEBUG_PORT}

services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    image: nginx:1.21.4
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  php-fpm:
    container_name: ${PROJECT_NAME}_fpm
    restart: unless-stopped
    build:
      context: ./docker/fpm
      <<: *arguments
    volumes:
      - ./:/project/src
    networks:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway

  database-redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:6
    volumes:
      - ./storage/redis:/bitnami/redis/data
    networks:
      - backend

  database-mariadb:
    container_name: ${PROJECT_NAME}_mariadb
    restart: unless-stopped
    image: mariadb:10.7.1
    ports:
      - ${DB_PORT}:3306
    env_file:
      - env/mariadb.env
    volumes:
      - ./storage/mariadb:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
